Feat/hex support
ChimeraTK/DeviceAccess-CommandBasedBackend pull request #25
Opened 2024-11-04 14:29 UTC by fiveisgreen

Hexidecimal register support added, as well as a test for Hex support.

2024-11-05 10:35 UTC, killenb requested changes
The writing is not working. The test does not detect it due to a bug.

What is also needed it to test that we can define writing with and without the leading ```0x```.

2024-11-05 10:35 UTC, killenb commented on src/CommandBasedBackendRegisterAccessor.cpp
Line 206 does not produce hex representation strings.

2024-11-05 10:35 UTC, killenb commented on tests/DummyServerLib/DummyServer.cpp
> +      }
You picked an unnecessarily complicated syntax for the hex command. Just positional, fixed number arguments would be sufficient. The rest is tested already, so we can concentrate on the hex part of it.
We should also test the mixed writing (last argument must not have 0x extension)
```HEX 0x12bab 0xd0d010 acbdef```
```
HEX?
0x12bab 0xd0d010 acbdef
```

2024-11-05 10:35 UTC, killenb commented on tests/testCommandBasedBackendUnified.cpp
> +  static bool isWriteable() { return true; }
Hm, the test is writing. It is enabled, but why does it not fail?

2024-11-05 10:35 UTC, killenb commented on tests/testCommandBasedBackendUnified.cpp
> +      v[e] = userTypeToUserType<UserType>(dummyServer.hex[e]);
Aha, that's why the test passes. It does not require the text to be a hex representation. This is just taking the integer string, interprets it as integer and returns the correct number.
 It is missing force0xHex() here.
 
 I am wondering if we should interpret the string and store the value, and then getRemoteValue() returns the stored value. In principle it does not matter where we interpret the string. However, we also need it in setRemoteValue, so we should do it in  DummyServer::setHex().

2024-11-08 12:26 UTC, fiveisgreen commented on src/CommandBasedBackendRegisterAccessor.cpp
> +        }
While this is nice, it creates a hazard where 0x is omitted in the config file, resulting in userTypeToUserType receiving "0x0x1234". So, there ought to then be a check that that 0x is absent, else throw an error.

2024-11-08 12:31 UTC, fiveisgreen commented on include/stringUtils.h
> +[[nodiscard]] std::string force0xHex(const std::string& str) noexcept;
Ok, we can do that. We still need that logic in the DummyServer, but can be moved there. Removing it also creates the issue

2024-11-08 12:37 UTC, fiveisgreen commented on src/CommandBasedBackend.cpp
The correction to the comment needs a home. Should it go directly into the master, or some new patch branch?

2024-11-11 15:42 UTC, killenb approved these changes
Approved after applying the suggestions.

Before merging:
* Test that all tests are passing (coding style test was again failing!)
* Squash everything into one commit (onto 6989ba9)
* Rebase onto master

2024-11-18 13:24 UTC, merged